# Generated by Django 2.2 on 2019-05-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190530_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='datanasc',
            field=models.DecimalField(decimal_places=4, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.IntegerField(null=True),
        ),
    ]
