# Generated by Django 2.2 on 2019-05-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190530_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='datanasc',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
